import Footer from '@/app/shared/widgets/Footer';
import './globals.scss';
import Navbar from './shared/widgets/Navbar';

export const metadata = {
  title: 'KTBL',
  description: 'Generated by create next app',
};
/* tslint:disable:no-empty */
async function RootLayout({ children }: { children?: React.ReactNode }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Navbar isHome={true} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
export default RootLayout;
